### ISSUE TITLE
check-spelling lacks a security policy

### ISSUE THREAD

**Issue by justinsteven** [check-spelling/check-spelling#13]
Please create a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) so that people know how to reach out to you regarding security vulnerabilities.

Also, can you please contact me via Twitter DM (<https://twitter.com/justinsteven>) or let me know how I can contact you regarding a vulnerability.

**Comment by jsoref** [comment]
https://twitter.com/_check_spelling

**Comment by jsoref** [comment]
6c4b24ea02e12256a35f8db26a4fc15cce977556
