### ISSUE TITLE
Ignore the I prefix when check spelling

### ISSUE THREAD

**Issue by yufeih** [check-spelling/check-spelling#14]
It is a convention in some programming languages to prefix an interface with `I`, like `IServiceProvider`. Today spell check does not recognize such naming convention and thinks `IService` is an unknown word. The `patterns.txt` does not work here because we want to also detect spelling problems if `Service` is misspelled.

**Comment by jsoref** [comment]
You could try:

```
# IServiceProvider
\bI(?=(?:[A-Z][a-z]{2,})+\b)
```

If that works, I can add it to the samples.

It seems to work when testing w/ https://www.regexplanet.com/advanced/perl/index.html

Please let me know.

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-patterns/_compare/0cdaed3e3475175f00385f259fcdb71a7cba5edf...fd9bbbbdb1892e367adcf6d5cc379ba3f8c74061

**Comment by yufeih** [comment]
@jsoref , will that `pattern` report the _Sevice_ typo if I write `ISeviceProvider` ?

**Comment by jsoref** [comment]
Before:
https://github.com/jsoref/examples-testing/commit/57e353487f12c4283b2da5d5a37828afb6e16705#commitcomment-54123215
After:
https://github.com/jsoref/examples-testing/commit/411762b3bf6e79743e8134f051a1de7518d4f7c7#commitcomment-54123225
