### ISSUE TITLE
occurring 'non-alpha-in-dictionary' warning for comments in expect.txt

### ISSUE THREAD

**Issue by tobi50** [check-spelling/check-spelling#16]
Hello, thank you for developing good tools like this!

I have trouble adding comments in setting expect.txt.
I read below about comment in expect.txt.
> comments in expect
> You can use # followed by text to add a comment at the end of a line. Note that some automatic pruning may not properly handle this.
> https://github.com/check-spelling/check-spelling/wiki/Configuration#comments-in-expect

But now I see warning 'non-alpha-in-dictionary' for comments in expect.txt.
I guess it is occurred by below codes and it will get better to fix regular expression.

https://github.com/check-spelling/check-spelling/blob/436362fc6b588d9d561cbdb575260ca593c8dc56/unknown-words.sh#L350-L363

I think changing below fix this,

`unexpected_chars="[^a-zA-Z']"`
to
`unexpected_chars="[^a-zA-Z'#]"`

and

`/^${expected_chars}*(${unexpected_chars}+)/`
to
`/^${expected_chars}+(${unexpected_chars}+)/`

Best Regards,

**Comment by jsoref** [comment]
Oh, indeed. Thanks for the input. I'll fix that in the next release.

I suspect I'll fix it differently, since I think I want to allow `#.*`

**Comment by tobi50** [comment]
Thank you for your quick responce!

**Comment by jsoref** [comment]
Fwiw, I have a fix for this in `prerelease`, but I'm still working on some of the other things I have in progress. https://github.com/check-spelling/check-spelling/commit/2f645046fa32f634bc128901b46db410aca36e5c
