### ISSUE TITLE
Spell checking is now case sensitive?

### ISSUE THREAD

**Issue by yufeih** [check-spelling/check-spelling#24]
Starting from recently, our spell checking started to [fail](https://github.com/dotnet/docfx/pull/7875). It seems like spell checker now reports unrecognized words even though they were listed in `expect.txt`:

Example report: https://github.com/yufeih/docfx/commit/6f3c3d0101af1e63aa3d039476a8397c08dcb512#commitcomment-66147695
The corresponding [`expect.txt`](https://github.com/yufeih/docfx/blob/fix-spell-checker/.github/actions/spelling/expect.txt)

Take `MEMORYSTATUSEX` as an example, the `expect.txt` contains an entry for `memorystatusex`

**Comment by jsoref** [comment]
If you switch `expect.txt` from `memorystatusex` to `MEMORYSTATUSEX`, I think it should fix what you're seeing.

The core design was built around being slightly case favoring. If you had `memorystatusex` in `expect.txt` and you had `MEMORYSTATUSEX` and `memorystatusex` in your repository, it'd be happy, but if you removed `memorystatusex` it'd encourage you to switch the entry in `expect.txt` entry to `MEMORYSTATUSEX`.

The logic for managing this is unfortunately complicated both for the code and to explain to end users, so I'm considering just removing it and making the entire system case sensitive.

I spent a bit of time on Sunday trying to massage the behavior and it didn't do what I wanted...

**Comment by yufeih** [comment]
Never mind, I am able to update `expect.txt` using the command in the comment, works beautifully.
