### ISSUE TITLE
How spell of commit message ?

### ISSUE THREAD

**Issue by patsevanton** [check-spelling/check-spelling#27]
Hello! I try use github action check-spelling/check-spelling for spell of commit message.
But check-spelling/check-spelling don`t spell commit message.

My repository https://github.com/patsevanton/correct-spelling-of-commit-message
My github action https://github.com/patsevanton/correct-spelling-of-commit-message/blob/main/.github/workflows/spelling.yml
Setting https://github.com/patsevanton/correct-spelling-of-commit-message/tree/main/.github/actions/spelling

Github action output https://github.com/patsevanton/correct-spelling-of-commit-message/runs/6785773673?check_suite_focus=true

**Comment by jsoref** [comment]
There isn't currently a provision for this. I haven't really thought about how it would work. Can you describe what you'd like it to do?

Should it only check the latest commit, all commits in the pr, or the entire history leading to the commit?

**Comment by antonpatsev** [comment]
Could only check the latest commit ?

**Comment by jsoref** [comment]
Yeah, I could. I'll try to do something soon, but it might be a bit. Note that it won't be by default as many consumers are unlikely to want this. It'll be a configurable thing, like checking file names.

**Comment by antonpatsev** [comment]
Thanks!

**Comment by jsoref** [comment]
I'm putting my thoughts here: https://github.com/check-spelling/check-spelling/wiki/Feature:-Check-commit-messages
