### ISSUE TITLE
How to enable this in my repo

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [check-spelling/check-spelling#28]
Please instruct me.

**Comment by jsoref** [comment]
You should be able to drop this file: https://raw.githubusercontent.com/check-spelling/spell-check-this/main/.github/workflows/spelling.yml into the `.github/workflows` directory.

**Comment by MrKrishnaAgarwal** [comment]
🆗 Done 
Then?

**Comment by jsoref** [comment]
It should run on push/pull request. Can you point to the repo where you've added the file?

**Comment by MrKrishnaAgarwal** [comment]
Thanks,
I was able to do it 
If I have any other queries,
I'll open another issue.
