### ISSUE TITLE
Last word in expect/allow files fail if there isn't an empty line

### ISSUE THREAD

**Issue by tas50** [check-spelling/check-spelling#29]
I have a few words added to my expect.txt and allow.txt files. If I forget to add an empty line at the end the last word of those files will fail. Adding the empty line so that the last word includes a carriage return seems to fix it all.

**Comment by jsoref** [comment]
What version of check-spelling? I thought I fixed that a while ago (it should warn about this but not actually break).

**Comment by jsoref** [comment]
Fwiw, I just released v0.0.21 a few hours ago.

Yeah, I'm pretty sure this is fixed. I might have time tonight to find the version where I fixed it...

**Comment by jsoref** [comment]
I *know* there were versions where this was a problem.

[0.0.14-alpha](https://github.com/check-spelling/check-spelling/releases/tag/0.0.14-alpha) introduced a warning for [no-newline-at-eof](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#no-newline-at-eof) as well as generally fixing the problem w/ it not handling that entry.

I _think_ I may have at times not properly handled DOS line endings in these files later versions...

That said, I've tried to reproduce this problem using a sample repository w/ various settings and really can't make it happen.

As @ricardo-dematos notes, this issue should not be present in the current release ([v0.0.21](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.21)).

**Comment by jsoref** [comment]
This 666e47280e5c5ada3ee46c9f67d0c8ed9ac74a13 regressed this. -- Actually, it was worse, in that it actively ate the text whereas before it just confused the engine...

I've fixed it (again) in `prerelease`.

**Comment by jsoref** [comment]
It's broken in v0.0.21. It'll be fixed in v0.0.22.

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 is now available
