### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by GaboFDC** [check-spelling/check-spelling#3]
From reading the readme, there are things still not clear. Would be  good to specify:

- Required variables
- example usage, in various cases (when using GitHub, a local folder, etc)
- the minimum required files. right now is really unclear all the files that you need to setup to get the action going.

It also would be nice if the action had defaults for all, and you didn't need to add any file to get started, and only add the files when you need to customize.

**Comment by jsoref** [comment]
Thanks for the feedback.

I'm definitely working on this. I think with 0.0.17 the `expect` file will be optional, and it should do a better job of suggesting things (although I doubt many people will be able to run without one in general, unless they actively use `allow` instead).

I suppose I could have a default for `bucket`/`project`, that initially felt a bit odd. I'm open to feedback, what do github actions normally do for settings? -- I think I'm just going to make a setting called `config` and give that a default (which will lose to `bucket`/`project` so as to not break compatibility)

I've generally used `.github/actions` (since switching to in-tree) for the bucket, for the project, I started with `spelling-data` and have moved towards `spelling`/`spell-check` (I'm open to input about which to use).

I've been slowly thinking about defaults, hoping to select them based on implementation experience...

I think I've managed to get the `GITHUB_TOKEN` to cooperate automatically for 0.17.

I'm also trying to figure how to deal w/ common word sets and patterns, is it sufficient to offer a bunch of things people can copy, or should I make it possible for people to opt-in? (Common computer terms, Language sets, API sets, Emoji sets, HTML tags, CSS terms) -- As many of these evolve over time, I'm slightly hesitant to offer them, it's easier for me to just encourage consumers to provide the things they're using.

**Comment by GaboFDC** [comment]
About the settings, I think what can be done, it that the action will work without any `bucket`/`project`, and use a minimal from the within the action. This will cause that just setting up the action, will work but you will be trigged for a lot of words, but this is expected, and then the user can specify the `bucket`/`project` to start adding his config.

I agree that provding a huge starting config is not a good idea, as as you said it is changing and dynamic, but offerin a really limited starting config can work.

**Comment by jsoref** [comment]
I'm trying to move to using the [wiki](https://github.com/check-spelling/check-spelling/wiki), for the next release, I've created [Quick-Start](https://github.com/check-spelling/check-spelling/wiki/Quick-Start) and [Configuration-information](https://github.com/check-spelling/check-spelling/wiki/Configuration-information)

Can you look over that and let me know how it looks?

I think I'm close. Hopefully I'll be able to simplify the README (just pointing to the wiki) and cut a release soon....

**Comment by krtschmr** [comment]
example config file for a quick plug&play is very useful

**Comment by jsoref** [comment]
@krtschmr: copying the contents from https://github.com/check-spelling/spell-check-this/ should be enough.

Out of curiosity, would it be helpful for the template to have each possible file w/ a comment containing a link to samples?

e.g.:
`excludes.txt`:
```
# see https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-excludes
```
`only.txt`:
```
# see https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-only
```
`patterns.txt`:
```
# see https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-patterns
```
`allow.txt`:
```
# one word per line -- items here will be added to the dictionary
```
`reject.txt`:
```
# one word per line -- items here will be removed from the dictionary
```

**Comment by krtschmr** [comment]
@jsoref  if this is enough (https://github.com/check-spelling/spell-check-this/blob/master/.github/workflows/spelling.yml)  then i would include this into the Readme. It's good practice to have a quickngo config ready so people can try out quick without any modifications or thought processes 

(i'll give it a try tomorrow)

**Comment by jsoref** [comment]
@krtschmr: did it work?

**Comment by krtschmr** [comment]
@jsoref haven't looked more into. i have a PR for our project with another tool which isn't merged yet. maybe i can try this one out tomorrow agtain

**Comment by LukeStorry** [comment]
Just copying the `.github` directory from this repo worked really well for us, but figuring that out took a bit of a read through the wiki, which I didn't even realise was there at first. Perhaps having that step as a "Quick Setup" section near the top of the main Readme might be nice, and more closely matches what other tools do. Perhaps also a link to the wiki near the top of the readme (I thought this is what the "More Information" link was going to take me to) would be nice to show there is some good documentation upon initial browse of the repo when deciding which tool to use.

**Comment by jsoref** [comment]
Thanks @LukeStorry. I'll probably make those changes soon. I'm hesitant to make changes to the `master` branch here until I'm confident about them (I don't like public churn). I do have a `prerelease` branch where I put things I'm experimenting with (things come/go/get reordered while I'm still developing).

**Comment by jsoref** [comment]
The wiki was an experiment because of my hesitancy to churn the repository and my uncertainty of how well the wiki itself would work. I think at this point, I've decided the wiki works pretty well, so it's time to make it more prominent. Similarly with spell-check-this and the examples content in the wiki.

**Comment by jsoref** [comment]
@GaboFDC, @LukeStorry: I've updated the readme (removing most the configuration -- just pointing to the wiki) and made spell-check-this more prominent. Let me know what you think.

**Comment by LukeStorry** [comment]
Looks good :)

**Comment by jsoref** [comment]
@krtschmr: I'd love to hear if it worked for you.

I think I'll close this issue shortly, as I believe I've addressed it by improving the root readme and making the spell-check-this repo more complete.

I'm still thinking about whether I should include a readme in the spell-check-this repo root, suggesting people copy out only the `.github` directory -- I understand it's odd to have a repo that doesn't have a readme in the root, but I'm a little worried that having one risks someone overwriting their actual project's readme... -- I'm open to input on this.

**Comment by krtschmr** [comment]
should we link straight to https://github.com/check-spelling/spell-check-this/blob/master/.github/workflows/spelling.yml ?

**Comment by jsoref** [comment]
@krtschmr: you can just drop that into your workflows directory, you'll want to add some files to `.github/actions/spelling/` (probably an `excludes.txt`, probably a `patterns.txt`, the bot will suggest content for `expect.txt`).

A future version (currently in prerelease) will even suggest some content for `excludes.txt` based on the repository.

**Comment by jsoref** [comment]
FWIW, I'm hoping to release the things I've described above this week.

One minor warning: I'm in the process of changing from `master` to `main` for the default branch. You'll still be able to use `master`, and at some point it'll start warning about the fact that `master` is no longer the default branch.

I think for 0.0.18 I'm going to drop the `-alpha` suffix from my versioning.

I'm hoping the release will have a slightly more polished look.

**Comment by jsoref** [comment]
@ricardo-dematos: hmm, it's part of https://github.com/check-spelling/check-spelling/wiki/Configuration#workflow-parameters. 

`Advanced` is really a collection of _almost deprecated_ and _debugging_ items. -- I'm not quite sure what to do about it. I suppose I could split them into two things or merge them back and make distinct sections.

For now, I've added a bunch of links back from that page to configuration, which should hopefully clarify things.

**Comment by jsoref** [comment]
Fwiw, I did add a https://github.com/check-spelling/check-spelling/blob/main/README.md#basic-configuration ala the suggestion by @krtschmr in https://github.com/check-spelling/check-spelling/issues/3#issuecomment-755533262 (thanks!).

**Comment by jsoref** [comment]
I've tried to update [only_check_changed_files](https://github.com/check-spelling/check-spelling/wiki/Configuration#only_check_changed_files). Let me know if that's helpful.

**Comment by jsoref** [comment]
I'm including another refresh to the README in the next release. I'll close this ticket then.

Afterwards, we can file new issues for specific changes.

**Comment by krtschmr** [comment]
awesome!

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 is now available
