### ISSUE TITLE
Control severity of sarif reports

### ISSUE THREAD

**Issue by VictoriousRaptor** [check-spelling/check-spelling#43]
In [wiki](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions) I see that user can configure specific events like `unrecognized-spelling` as warning, but I can't find any example or hint to apply it.

**Comment by jsoref** [comment]
I've made the following changes:

1. Added a [page documenting the feature](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Treat-specific-errors-as-warnings)
2. Updated the [v0.0.20 release notes](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.20) and [wiki entry](https://github.com/check-spelling/check-spelling/wiki/Release-notes#v0020)
3. Added a link from [Event descriptions](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#event)

**Comment by jsoref** [comment]
Please let me know if this covers what you're looking for / if you have any problems.

**Comment by VictoriousRaptor** [comment]
Thank you for your reply! Now I can treat unrecognized spellings as warning in action log. But is there a way to treat it as warning in Security tab of my repo?

**Comment by jsoref** [comment]
Oh, interesting, you're using Sarif? Not currently, how much control do you want/need? I could allow you to specify a replacement [Sarif template](https://github.com/check-spelling/check-spelling/blob/main/sarif.json)... Or I could provide a thing similar to the warnings flag, or I could try to apply the values from `warnings` into the Sarif template.

One concern I have w/ letting you replace the file entirely is that when you upgrade, you'd lose whatever new items it defines. `warnings` behaves a little differently in that it will only override things you know about and everything else you effectively inherit.

(I'd love to get feedback on your experience of using Sarif, it's a new feature and I don't think many people have deployed it yet.)

**Comment by jsoref** [comment]
I've also added warnings to https://github.com/check-spelling/check-spelling/wiki/Configuration#warnings. I'll need to spend some time reviewing the full list to see if I've missed anything else...

**Comment by jsoref** [comment]
Thinking about the Sarif side a bit, I think what I'll do is let you write a `sarif.json` file, and if there is one, I'll merge its contents into the `sarif.json` file I have, probably using code similar to:
https://gist.github.com/theimpostor/79d4d37876aa990edd2ebc0e1d9391b5

That's pretty workable, since `prerelease` handles the `sarif.json` using `JSON::PP`:
https://github.com/check-spelling/check-spelling/blob/07584a3f1cddca386eefde7a2d3a02db90cf070a/generate-sarif.pl#L38

I suspect I'll look into this the next time I look at the Sarif handling (probably in a week or two).

**Comment by VictoriousRaptor** [comment]
I've temporaily disabled sarif since it's spamming the repo's security tab. Please inform me when it's polished better.

> how much control do you want/need? 

My request is to treat events defined as warning in the yml file as warning in sarif too. Or the security tab is full of error alerts.

Thank you for creating this amazing repo!

**Comment by jsoref** [comment]
I've implemented a version of this in: d5a7faad26dfca0d2a1187bfb222d41cbffa1c4b.
You can try using `@prerelease`.

Just drop in a file, something like https://raw.githubusercontent.com/check-spelling/check-spelling/prerelease/t/sarif.json into `.github/actions/spelling/sarif.json` (assuming you're using `.github/actions/spelling`), its content will be merged with the general https://raw.githubusercontent.com/check-spelling/check-spelling/prerelease/sarif.json file, things you define should override things in the base file. (The version field is set by check-spelling after this, so you won't be able to set it, and similarly the `results` are filled in after merging your override.)

I'd love to get some feedback before this ships.

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 is now available
