### ISSUE TITLE
PR comments don't always get collapsed if spelling errors are fixed

### ISSUE THREAD

**Issue by Piedone** [check-spelling/check-spelling#44]
Based on what I've seen Check Spelling doing, and https://github.com/check-spelling/check-spelling/issues/23 I'd expect the comments under a PR to get minimized like this, if in a later commit the spelling errors were corrected:

![image](https://user-images.githubusercontent.com/1976647/210867110-a4fc23f9-57dc-4a1e-9996-d63ad51ad4dc.png)

This sometimes happens but sometimes not. As of yet, I can't correlate it with anything.

E.g. [this comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/352#issuecomment-1371515806) is properly collapsed and was added at 10:48 PM UTC on 4 January. [This comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/352#issuecomment-1372300778) under the same PR isn't, and it was created at 2:37 PM UTC on 5 January. Between these only [this commit](https://github.com/Lombiq/GitHub-Actions/commit/34a5bc0d07d2a0266c1c7ffb4e1090f17adbd229) happened to the config but that shouldn't cause it. Also, [this uncollapsed comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/349#issuecomment-1370218101) was added on 3 January, so it's not related to some changes we made in the config.

**Comment by jsoref** [comment]
I think your workflow is using:
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3847653530/workflow#L41-L47

I think you'd be able to "fix" this with a second job, admittedly, you'd want to define a reusable workflow for it and have it fill in the other bits based on the first one.

I looked into trying to write a reusable workflow to make this stuff clean and the effort made me shrug them off because of the amount of duplication it required...

**Comment by Piedone** [comment]
Thank you for your quick reply.

Yes, the job that's running spell-checking is [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3847653530/workflow#L41-L47), which calls into a reusable workflows, which in turn calls a composite action [here](https://github.com/Lombiq/GitHub-Actions/blob/34a5bc0d07d2a0266c1c7ffb4e1090f17adbd229/.github/workflows/spelling.yml#L73-L79). That action then calls `check-spelling` [here](https://github.com/Lombiq/GitHub-Actions/blob/34a5bc0d07d2a0266c1c7ffb4e1090f17adbd229/.github/actions/spelling/action.yml#L45-L55) (the action also has configuration files in [its folder](https://github.com/Lombiq/GitHub-Actions/tree/34a5bc0d07d2a0266c1c7ffb4e1090f17adbd229/.github/actions/spelling)).

So if I understand correctly, we need two jobs for `check-spelling` (when running for PRs):

1. One [like this](https://github.com/check-spelling/spell-check-this/blob/9c3ef4d7167d6dfa39d3040e763c5e7df8f6c681/.github/workflows/spelling.yml#L56-L85).
2. One depending on the previous one [like this](https://github.com/check-spelling/spell-check-this/blob/9c3ef4d7167d6dfa39d3040e763c5e7df8f6c681/.github/workflows/spelling.yml#L103-L117).

Can you please confirm?

Do these need to be two jobs, or can they be two steps in the same job? If two jobs, then we need to put them into the linked reusable workflow. If two steps, then they can be in the composite action.

**Comment by jsoref** [comment]
The design assumes that the first stage doesn't have write permissions and the second does. Since permissions are assigned at a job level, to safely operate in a public repository you should use two jobs.

**Comment by Piedone** [comment]
I see, thank you, will try.

**Comment by jsoref** [comment]
@Piedone: did it work?

**Comment by Piedone** [comment]
One of our colleagues is working on it. I hope we can have some results soon.

**Comment by 0liver** [comment]
@Piedone I think we're done here - [our PR](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/399) for this issue has been merged a while back.

**Comment by Piedone** [comment]
Yep, thanks.
