### ISSUE TITLE
Strange partial word failures

### ISSUE THREAD

**Issue by tas50** [check-spelling/check-spelling#47]
This is 100% probably me doing something dumb with a rule, but I'm quite confused at this point. In this PR I removed a catch-all regex that was introduced, and now I'm getting odd partial word failures that aren't showing up in the PR itself:

https://github.com/mondoohq/cnspec/pull/341

Any idea why these funky partial words are getting added? Apologies in advance if this is something super 🤦

**Comment by jsoref** [comment]
Well, I can tell you it's something in the README.md file 😉.

**Comment by jsoref** [comment]
The problem is:

```
# docker container
[a-z,0-9]{12}
```

**Comment by jsoref** [comment]
Here's the reduced file: https://raw.githubusercontent.com/check-spelling/cnspec/1bcd6b34af44302f1762cbe7d5de739198a7f994/README.md
Here's a run that's happy: https://github.com/check-spelling/cnspec/actions/runs/4140361326
and here's a run that's unhappy: https://github.com/check-spelling/cnspec/actions/runs/4140353337

The reason that check-spelling isn't identifying your "word" is that it tries to find _words_, and what we have here is a substring that's been lopped from a word.

I could construct an example to explain the problem, but basically it'd be something like:

```
The fuzziest armies&apos; vulnerabilities; allies&#39; assets aren't everything.
```

The pass that reports the offsets uses the original unmodified line whereas the scanner that looks for unknown words uses the masked version:

```
The fuzziest armies' have ============ies allies' assets aren't everything=
```

When it goes to find your word, it wants to give valid offsets, which aren't a perfect match to where it was parsing.

I should probably have it spit out the line number and an apology / explanation. That'd help everyone.

**Comment by jsoref** [comment]
Here's an improved version: https://github.com/check-spelling/cnspec/actions/runs/4141241682#summary-11244757055

This will be available in the next release. Thanks for providing the input and giving me time to think about how to resolve it.

If you have other ideas about this or other things, please don't hesitate to let me know.

**Comment by tas50** [comment]
That'll be a great addition to troubleshooting this sort of thing. Thanks for digging in. This one was stumping me.
