### ISSUE TITLE
`\n` seems to be interpreted as newline, and words containing it cause error

### ISSUE THREAD

**Issue by 0liver** [check-spelling/check-spelling#48]
### Version: 0.0.21, commit d7cd2973c513e84354f9d6cf50a6417a628a78ce

I've just added some documentation to one of our projects which contains these lines:

```md
e.g. _%AppData%\npm\etc\npmrc_.
rmdir -r "$env:ProgramFiles\nodejs"
```

After that, the check-spelling action started to complain about `odejs` and `pmrc` being unrecognized words. Looks very much like the remainders of the lines above after splitting! Here's a [link to the failing GHA run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4281398662/jobs/7454375054#step:4:259).

I would categorize this as a bug. Is there a way to work around this?

**Comment by jsoref** [comment]
Add a pattern of `\\npm` or similar.

A more complete example for this would be:
```
\\n(?:ode|pm)
```

Unfortunately, these three characters: `\n`, `\r`, `\t` have built-in (from day 0) handling.

It's a huge behavior change to remove that built-in handling, although some recent changes I've made will make it much more tolerable.

(I'll be able to move them from where they currently live to candidates and then people could omit them directly.)

I think I'll be able to safely migrate this from its current status as a built-in with the next release. I'll try to play w/ that change this week.

**Comment by 0liver** [comment]
Thanks for your quick answer! Customizing this sounds exciting, but might be overkill.

In the meantime, I've found a workaround: Markdown actually [supports escaping](https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/escaping-characters.md#characters-you-can-escape) those backslashes, which is what I did, and now your spell checker doesn't choke on them anymore!

So, with these two options, escaping or adding a simple pattern, I'd be fine with closing this issue.

**Comment by jsoref** [comment]
It's ok, I've been wanting to remove this built-in for a while.

**Comment by jsoref** [comment]
Fwiw, the code is here:
https://github.com/check-spelling/check-spelling/blob/d7cd2973c513e84354f9d6cf50a6417a628a78ce/lib/CheckSpelling/UnknownWordSplitter.pm#L306

-- yes, it specifically understands that `\\n` is an escaped `\` and ignores it (resulting in the `npm` being seen as its own token).

Fwiw, I've been running w/ this change in prerelease for a while and I'm quite happy with it: https://github.com/check-spelling/check-spelling/commit/d67bf003686ff76fcf128ed018db27a6820334be

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 is now available
