### ISSUE TITLE
Remove obsolete words doesn't work. 

### ISSUE THREAD

**Issue by lilith** [check-spelling/check-spelling#5]
I've not been able to get the remove obsolete words step to run (it throws no errors, but changes no files). 

https://github.com/imazen/imageflow/commit/45800a4d7eb5794e95f0c7e33318173eca9399ae

**Comment by jsoref** [comment]
Thanks. That's a line endings thing. I've fixed it locally. I need to test a bit, but I'll probably make a release today for it.

(You're one release out of date which you'll want as well, but it probably makes sense to skip that release and get the one w/ this fix.)
