### ISSUE TITLE
Content masked by `patterns.txt` shouldn't count to minified ratio

### ISSUE THREAD

**Issue by Piedone** [check-spelling/check-spelling#53]
[This Markdown file](https://github.com/Lombiq/Hosting-Tenants/blob/496911df6cb8c8a1f1fbdc70bb21cd17b12395b5/Readme.md), a Readme, has a long line at the top (containing NuGet shields; this needs to be one line as enforced by MD linting). `check-spelling` (v0.0.21) ignores this file with the following warning:

> Skipping `src/Modules/Lombiq.Hosting.Tenants/Readme.md` because average line width (1047.33333333333) exceeds the threshold (1000). (minified-file)

However, it's not a minified file and should rather be checked.

~So, I'd suggest one or more of the following options:~

- [x] If a line is ignored by `patterns.txt`, then that ignore also takes effect for this modification check. I.e. if I ignore the long line, the rest of the file should be checked still.
- [ ] ~Exclude .md files from the minification check.~
- [ ] ~Provide a more granular configuration instead of just blanket `disable_checks: minified-file`, like a pattern for file extensions to be excluded from this check.~

**Comment by jsoref** [comment]
Oh, factoring in patterns seems quite reasonable. It isn't a huge amount of overhead, just appending after-filtered line lengths and using that instead of a `tell` call.

I like that idea.

Implemented in 4dabda01 (in prerelease).

**Comment by Piedone** [comment]
Thank you for being so quick to respond. I don't really see how the linked commit implements this though, could you explain?

**Comment by jsoref** [comment]
When things are hit by patterns, they're currently masked (with `=`) instead of elided. This enables proper offset reporting for found items. The last step where it calculates the ratio used to take the current file position (using `tell`) and line number to calculate a ratio. With the change, it removes the runs of 3 `=`s which are presumed to not be minified content but are most likely pattern replacements and then sums the remaining line length to calculate the amount of content seen. (It will technically treat a really long line of `=`s that aren't a pattern replacement as nothing as well, but I don't think that's something that generally happens in minified content, so I'm ok with that false negative.)

Could you try using 2d274590429703ade45b4b96e3beb091f6bd0154 and see if it works?

**Comment by Piedone** [comment]
Ah OK, my whole misunderstanding stems from not seeing that by "patterns" you actually meant _patterns.txt_, not something like a separate configuration with an ignore pattern for disabling the minification check. All clear now.

I tested it out, and it works, no more warning: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/5114328703 Spell-checking otherwise in the same file still works as it should: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/5114372557

So, thank you!

**Comment by Piedone** [comment]
Whe do you intend to release v0.0.22?

**Comment by jsoref** [comment]
I'm hoping this week. I think I've done all of my code changes and am slowly beating the documentation into shape.

Can you give the current https://github.com/check-spelling/check-spelling/tree/prerelease a kick for a day?

**Comment by Piedone** [comment]
I tested it out and worked great, thanks. See https://github.com/Lombiq/GitHub-Actions/actions/runs/6227964134/job/16903732401?pr=234 and https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/6228059558/job/16904012854. I needed to fix an `ignored-expect-variant` error before that, [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/6228000584), but that's good.

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 is now available

**Comment by Piedone** [comment]
Awesome, thank you! Updated our GitHub Actions project: https://github.com/Lombiq/GitHub-Actions/pull/234
