### ISSUE TITLE
LaTeX commands misunderstood

### ISSUE THREAD

**Issue by ragonneau** [check-spelling/check-spelling#56]
Hi,

First, thank you very much for this work; it's very useful.

I am using it for several projects that have LaTeX files, and I face the following issue: the action interprets `\norm{...}`, `\transpose{...}`, ... (commands I defined) as `<newline>orm{...}`, `<tabulation>ranspose{...}`, ... Therefore, it indicates that the words `orm`, and `ranspose`, ..., do not exist. Is there any easy fix?

Thanks in advance for your kind help,
Cheers,
Tom.

**Comment by jsoref** [comment]
In the next version (`@prerelease`) it won't do this – if you're comfortable using prerelease, you could just switch. In the interim, you can copy this over to candidate.patterns or patterns.txt: https://github.com/check-spelling/spell-check-this/blob/5f0e813f331e985e1231dd140a7a570323d1958c/.github/actions/spelling/candidate.patterns#L560-L561

**Comment by jsoref** [comment]
In the next version (`@prerelease`) it won't do this – if you're comfortable using prerelease, you could just switch. In the interim, you can copy this over to candidate.patterns or patterns.txt: https://github.com/check-spelling/spell-check-this/blob/5f0e813f331e985e1231dd140a7a570323d1958c/.github/actions/spelling/candidate.patterns#L560-L561

If things actually have the form, you could try using this:
```
\\[nrt][a-z]+\{
```

**Comment by ragonneau** [comment]
Ok, thanks!

Cheers,
Tom.
