### ISSUE TITLE
`only_check_changed_filed` breaks with PR from fork in v0.0.22

### ISSUE THREAD

**Issue by VictoriousRaptor** [check-spelling/check-spelling#59]
When trying to run spell check job it raises an error and just exits. See [here](https://github.com/Flow-Launcher/Flow.Launcher/actions/runs/6495116898/job/17703565321).

Config is [here](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/.github/workflows/spelling.yml)

**Comment by jsoref** [comment]
I've made some changes: https://github.com/check-spelling/check-spelling/blob/a92b165537b6b138728b27b81cf6c24f7b9c5c59/unknown-words.sh#L1987-L2004 

Can you try using `@prerelease`?

**Comment by jsoref** [comment]
I've shipped https://github.com/check-spelling/check-spelling/releases/tag/v0.0.23, so you should be able to use it. Thank you for your feedback.
