### ISSUE TITLE
There should be a line magic to disable it

### ISSUE THREAD

**Issue by schorrm** [check-spelling/check-spelling#6]
Things where there's one line where I need a bunch of stuff there that'll trip it up. Something like:
// #nospellcheck my comment etc

**Comment by jsoref** [comment]
is the goal to have

```c
int myOdddddWord = 0; // #nospellcheck
```
?

Note that you can do this today by adding a `pattern.txt` file:
```
^.*// #nospellcheck.*$
```

**Comment by schorrm** [comment]
more `// #nospellcheck My oddddd comment`

**Comment by jsoref** [comment]
Ok.
Today you could do that w/ this in a `pattern.txt` file:
```
// #nospellcheck.*$
```

Is that sufficient? (I need to add sample documentation for such things -- I'm slowly working on improving my samples)

**Comment by schorrm** [comment]
Yup. Thank you!
