### ISSUE TITLE
no-files-to-check error when using only_check_changed_files and only changing GitHub actions

### ISSUE THREAD

**Issue by gwarf** [check-spelling/check-spelling#61]
Hi,
We are using the Check Spelling as a GitHub action, and we are getting [no-files-to-check](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#no-files-to-check) errors when using [only_check_changed_files](https://github.com/check-spelling/check-spelling/wiki/Configuration#only_check_changed_files) and when pushing changes touching only GitHub actions.
We are not making use of [only](https://github.com/check-spelling/check-spelling/wiki/Configuration#only) or [excludes](https://github.com/check-spelling/check-spelling/wiki/Configuration#excludes), and in fact I wouldn't mind when there are no files to check, that no error would be reported.
I saw that there were settings like [warnings](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Treat-specific-errors-as-warnings), but if possible I wouldn't want to have to specify the full lists of warnings, as it doesn't seem convenient in case new ones are added/removed.
Have you any suggestion on how to address this?
Thanks for your work!

**Comment by jsoref** [comment]
Yeah, I'm noticing that. I'll probably add a new thing to allow overriding specific items instead of just the whole set. Thanks for your feedback.

**Comment by jsoref** [comment]
In the interim, you'll indeed have to use `warnings`, e.g.:
```yaml
warnings: bad-regex,binary-file,deprecated-feature,ignored-expect-variant,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check
```

Sorry...

**Comment by gwarf** [comment]
OK, thanks for feedback!

**Comment by jsoref** [comment]
I've shipped https://github.com/check-spelling/check-spelling/releases/tag/v0.0.23, so you should be able to use it. Thank you for your feedback. 

You can now [set event severity](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Set-event-severity) for each category including ``ignored`.
