### ISSUE TITLE
Deprecation warning due to outdated actions/cache/save version using Node 16

### ISSUE THREAD

**Issue by Piedone** [check-spelling/check-spelling#63]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings like below under your workflow runs:

![image](https://github.com/check-spelling/check-spelling/assets/1976647/d30f28fd-d026-4a91-9bba-1c2cf8ba4dda)

(Ignore the `checkout` warning, that's used by our workflow.)

This is because `actions/cache` v3 used Node 16, but that was fixed: https://github.com/actions/cache/issues/1260. This will go away if you upgrade to v4.

**Comment by jsoref** [comment]
Yeah... I think I fixed it in prerelease this morning: https://github.com/check-spelling/check-spelling/commit/29a57c171b415fdd05fc34d8bd17f39ad2620598

**Comment by Piedone** [comment]
Ah, great timing! I'd suggest releasing this as soon as you can, since as of a few days ago, all users will see this warning (GitHub delayed showing the warning after the announcement since their actions weren't updated either).

**Comment by jsoref** [comment]
Yeah, I need to make sure that nothing breaks.

The actions/upload-artifact & actions/download-artifact change that GitHub made was a messy breaking change and it requires some actual testing of a bunch of corner cases (I did an initial implementation this morning and an internal consumer reported that I messed up midday, so I've fixed at least the basic case, I think, but I need to test the fancier case as we don't actively use it).

Sadly I'll probably need to cherry-pick a release as I have quite a few in-flight things and I don't really want to release most of them right now (I like taking my time on things)... cherry-picking isn't particularly hard in general, but it's effort.

This might end up happening on Tuesday or Wednesday... (I don't have much time Friday-Monday.)

**Comment by Piedone** [comment]
That would be still good, thank you.

**Comment by Piedone** [comment]
Any news on the release by chance?

**Comment by Piedone** [comment]
Sorry to be a bother, but could you publish a new release, please? The last one is from last September, and the Node deprecation is looming.

**Comment by jsoref** [comment]
The deprecation shouldn't actually do anything per https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Here's a run of check-spelling v0.0.22 using node20 instead of node16: https://github.com/check-spelling-sandbox/web-qa/actions/runs/8635992495 -- things seem to work fine.

---

I've done some testing with `act` and fixed some things (I generally try to do this before releases, as it tends to break).

I've just added a couple more things yesterday. 

I haven't hit any big snags (beyond a concussion 🤕 in March). So I really do hope I can get the next release out the door shortly.

**Comment by Piedone** [comment]
I'm sorry to hear about your concussion, but great, thank you!

Good to know that the action won't break at least, though it'd be nicer not to have the warnings either.

**Comment by Piedone** [comment]
Can you share when you intend to publish the release?

**Comment by lemeurherveCB** [comment]
> Can you share when you intend to publish the release?

@jsoref gentle ping 🙂

**Comment by jsoref** [comment]
Yeah... Sorry... holiday season plus other things. I'm looking into publishing it this week or next week.

**Comment by Piedone** [comment]
Thank you!

**Comment by jsoref** [comment]
I've shipped [v0.0.23](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.23). This issue ended up driving one of the more interesting improvements of the release: only downloading dependent actions as needed as well as fixing some upstream bugs (mostly in [github/codeql-action](https://github.com/github/codeql-action)). Thank you for your feedback.

**Comment by Piedone** [comment]
Great, thank you!
