### ISSUE TITLE
Improve handling of requests to use sarif with private repositories without Advanced Security

### ISSUE THREAD

**Issue by malcomio** [check-spelling/check-spelling#64]
I haven't been able to find a clear guide on how to get check-spelling working with private repositories.

Seems like it may be necessary to add a secret named `CHECK_SPELLING` in GitHub, but should that be a deploy key, a self-generated SSH key, something else?

Possibly related to #62

**Comment by malcomio** [comment]
https://github.com/check-spelling/check-spelling/wiki/Feature:-Update-with-deploy-key seems relevant

**Comment by malcomio** [comment]
Having followed the steps in [that wiki page](https://github.com/check-spelling/check-spelling/wiki/Feature:-Update-with-deploy-key), I'm encountering the following error:

> Warning: Code scanning is not enabled for this repository. Please enable code scanning in the repository settings.

Seems like code scanning is only allowed for public repos, or on paid GitHub plans: https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security

**Comment by jsoref** [comment]
Sarif is an optional integration feature in check-spelling. It is possible to pay GitHub to use sarif, but you probably should just remove the flag from the workflow. 

I'll change message to suggest removing the flag as an alternative to enabling Advanced Security.

check-spelling is supposed to fall back to the classic reporting, and not trigger any additional warnings/errors relating to sarif -- I'll have to see if there's a bug here. 

Could you try using `@prerelease` instead of `main` ?

**Comment by malcomio** [comment]
thanks - I've switched to use `prerelease`, and as far as I can see I've removed all the relevant flags from my config

have created separate repos - 

one private: https://github.com/malcomio/test-spell/pull/2
and one public: https://github.com/malcomio/test-spell-public/pull/1

will test further

**Comment by malcomio** [comment]
One thing that I hadn't realised is that the actions on my pull requests were using the version of the workflow as defined in the main branch, rather than the pull request branch.

So my configuration changes were being ignored until I merged them into main - i.e. `use_sarif` was still set to true

Having done that, I've been able to successfully check spelling on my private repo: https://github.com/malcomio/test-spell/pull/3 and https://github.com/malcomio/test-spell/pull/4

Would be good to improve documentation to help other users in future

**Comment by jsoref** [comment]
Yes, in order for check-spelling to be able to make comments on pull requests from forks, it needs to be run from pull_request_target, which means that changes to the workflow in pull requests are functionally ignored. 

I've been playing with parsing yml files recently, so I could probably recognize when the workflow has changed significantly in the pull request (alternatively, I could just flag when the file itself changes at all).

I think initially I'll add a sentence to the sample working file that tries to explain that changes to the file won't be reflected in pull requests, that should help things a little.

**Comment by jsoref** [comment]
I've shipped [v0.0.23](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.23). Thank you for your feedback.
