### ISSUE TITLE
`-latest` is wrongly detected as `atest` bad spelling

### ISSUE THREAD

**Issue by lemeurherveCB** [check-spelling/check-spelling#68]
On version 0.0.22 (and 0.0.21), we noticed that `-latest` is wrongly recognised as `atest`, see https://github.com/updatecli/updatecli/pull/2758

As a workaround we're adding `atest` in our exclude list for now.

Maybe `-` is the culprit here?

**Comment by jsoref** [comment]
Yes, it's caused by a pattern, see https://github.com/updatecli/updatecli/pull/2758#issuecomment-2404081162

**Comment by lemeurherveCB** [comment]
Thanks, and sorry for the noise 😅

**Comment by jsoref** [comment]
It's ok. At some point I'll probably enable discussions somewhere. I did experiment with them. You lucked out in that I was actively working on it. There have been/will be runs if days this month when I'm offline.
