### ISSUE TITLE
`followup` set to `collapse_previous_comment` for previously collapsed comment

### ISSUE THREAD

**Issue by Piedone** [check-spelling/check-spelling#70]
In v0.0.22 the [`followup` output](https://github.com/check-spelling/check-spelling/blob/b365ac888c4713bf3a082b07b342feed0f3438fe/action.yml#L352) was only set if spell-checking failed and thus a PR comment needed to be added. See e.g. [this run](https://github.com/Lombiq/GitHub-Actions/actions/runs/11456488627). In v0.0.23, however, it seems to be always set (see e.g. [this run](https://github.com/Lombiq/GitHub-Actions/actions/runs/11486189295?pr=393)).

I don't know if this is a problem, but it's a change in behavior so I wanted to bring it up.

For us, this causes a second job to run ([here](https://github.com/Lombiq/GitHub-Actions/blob/b679772039f5eb61726090825f11690544ca7fab/.github/workflows/spelling.yml#L132) even if it's not needed. This is not a big deal, just some unnecessary machine time usage.

**Comment by jsoref** [comment]
The task is `collapse_previous_comment` the design is such that it will collapse an existing comment if it finds one... The assumed model is that the main task doesn't have permission to add comments/collapse them. Otherwise your comments wouldn't be collapsed when your check-spelling report changes from :x: to ✅.

**Comment by Piedone** [comment]
Do I understand correctly then that the change in behavior is intentional?

**Comment by jsoref** [comment]
I'm not certain. `collapse_previous_comment` was present in 0.0.20, so I wouldn't expect you to trip on something different in 0.0.23. It's possible the logic is misbehaving, but if there was a comment from the previous run, then a new run should be collapsing it.

If [v0.0.22](https://github.com/check-spelling/check-spelling/commit/v0.0.22) (00c989c97749eb0cb2d256bdc55ac61b0096c6d3) didn't properly set followup to collapse_previous_comment, then it's possible there was a bug fix between it and [v0.0.23](https://github.com/check-spelling/check-spelling/commit/v0.0.23) (2c9e4a85102fa9b6df3cb8bb5a8dc8bdc2fb2fea). I don't recall one (we do use the feature, but it's been working for so long that I have absolutely no sense of when I might have changed it).

There was supposed to be a path that decided collapsing comments was required:
https://github.com/check-spelling/check-spelling/blob/00c989c97749eb0cb2d256bdc55ac61b0096c6d3/unknown-words.sh#L3020-L3029

And both cases were supposed to be produced:
https://github.com/check-spelling/check-spelling/blob/00c989c97749eb0cb2d256bdc55ac61b0096c6d3/unknown-words.sh#L2592-L2596

The handling as of 22 supported two cases:
https://github.com/check-spelling/check-spelling/blob/00c989c97749eb0cb2d256bdc55ac61b0096c6d3/unknown-words.sh#L23-L25

The code doesn't seem to have changed significantly between the two versions.

---

That said, your two runs show that the code picked the same comment to collapse twice, and afaict it properly collapsed it the first time, which means that there's something wrong with the logic to decide that it needs to collapse a comment.

As such, I'm retitling this issue to describe what appears to be going wrong (the original description didn't describe what `followup` meant -- there was a time (prior to 0.0.020) when it really would only set followup to `comment`).

**Comment by Piedone** [comment]
Looks good now, thank you:

- Passing spell-check correctly doesn't have anything in `followup`: https://github.com/Lombiq/GitHub-Actions/actions/runs/11523741810?pr=394
- Failing does: https://github.com/Lombiq/GitHub-Actions/actions/runs/11523786909

**Comment by jsoref** [comment]
Right, that's the design. I might ship a release next week with just a couple of fixes...

**Comment by Piedone** [comment]
Great!

**Comment by jsoref** [comment]
Fixed in https://github.com/check-spelling/check-spelling/releases/v0.0.24
